#!/bin/bash

if [ $# -lt 1 ]; then
	echo "Usage: $0 <file> [length] [-d]" >&2
	exit 1
fi

file="$1"
shift

len=2
if [[ "${1:-}" =~ ^[0-9]+$ ]]; then
	len="$1"
	shift
fi

java -cp target/string-constraint-solvers-1.0-SNAPSHOT-jar-with-dependencies.jar edu.boisestate.cs.SolveMain "$file" -l "$len" "$@"
